# flow name
name: Frontend Deploy
# 什麼時候觸發
on:
  # 在 push code 時觸發
  push:
    # 什麼 branch 要觸發
    branches:
      - "master"
      - "other"

# 觸發時要做什麼
jobs:
  # 要 build app
  build:
    # build 的環境
    runs-on: ubuntu-latest
    # build 依序要做哪些事情
    steps:
      # 使用別人做好的 action, 這個 action 是 checkout 到對應的 branch
      - uses: actions/checkout@v2

      - name: Login Docker
        # 執行登入 docker 的 command
        run: docker login -u ${{secrets.DOCKER_NAME}} -p "${{secrets.DOCKER_PASSWORD}}"

      # 創建要放到 aws 的檔案
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ESB
        # 使用別人做好可以上傳到 ESB 的 actions
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "webrtc-practice"
          environment_name: "Webrtcpractice-env"
          existing_bucket_name: "elasticbeanstalk-us-east-1-989896877158"
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
